require("bilguun.plugins-setup")
require("bilguun.core.options")
require("bilguun.core.keymaps")
require("bilguun.core.options")
require("bilguun.plugins.comment")
require("bilguun.plugins.nvim-tree")
require("bilguun.plugins.lualine")
require("bilguun.plugins.telescope")
require("bilguun.plugins.nvim-cmp")
require("bilguun.plugins.lsp.mason")
require("bilguun.plugins.lsp.lspconfig")
require("bilguun.plugins.lsp.lspsaga")
require("bilguun.plugins.lsp.null-ls")
require("bilguun.plugins.autopairs")
require("bilguun.plugins.treesitter")
require("bilguun.plugins.gitsigns")
vim.cmd([[colorscheme nightfly]])
